name: "build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
env:
  ARTIFACT_LINUX_X86_64_EXTENSION: sqlite.org-extensions-linux-x86_64
  ARTIFACT_MACOS_X86_64_EXTENSION: sqlite.org-extensions-macos-x86_64
  ARTIFACT_MACOS_AARCH64_EXTENSION: sqlite.org-extensions-macos-aarch64
  ARTIFACT_WINDOWS_X86_64_EXTENSION: sqlite.org-extensions-windows-x86_64
jobs:
  build-linux-x86_64-extension:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: ./configure && make sqlite3.c fts5.c
        working-directory: sqlite
      - run: make all
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_LINUX_X86_64_EXTENSION }}
          path: dist/*
  build-macos-x86_64-extension:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: ./configure && make sqlite3.c fts5.c
        working-directory: sqlite
      - run: make all
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_MACOS_X86_64_EXTENSION }}
          path: dist/*
  build-macos-aarch64-extension:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: ./configure && make sqlite3.c fts5.c
        working-directory: sqlite
      - run: make all CFLAGS="-target arm64-apple-macos11"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_MACOS_AARCH64_EXTENSION }}
          path: dist/*
  build-windows-x86_64-extension:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: find .
        working-directory: sqlite
        shell: bash
        #- uses: microsoft/setup-msbuild@v1.1
      #- run: choco install -y cygwin
      #- run: C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
      #- run: |
      #    autoconf.exe
      #    ./configure
      #    make all
      #  working-directory: sqlite/
      #  shell: bash
      #  # nmake /f Makefile.msc | sqlite3.c fts5.c
      - run: make all-no-fts5
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_WINDOWS_X86_64_EXTENSION }}
          path: dist/*
